version: '3.9'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: omnisync-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: omnisync
      POSTGRES_PASSWORD: omnisync
      POSTGRES_DB: omnisync
    ports:
      - "5432:5432"
    volumes:
      - omnisync-pgdata:/var/lib/postgresql/data
      - ./database/schema/init.sql:/docker-entrypoint-initdb.d/01_init.sql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: omnisync-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: omnisync
      RABBITMQ_DEFAULT_PASS: omnisync
    ports:
      - "5672:5672"
      - "15672:15672"  # management UI

  redis:
    image: redis:7-alpine
    container_name: omnisync-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  omnisync-pgdata:
